name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #network
  dio: ^5.8.0+1
  
  #state managment
  get: ^4.7.2

  #db
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  build_runner: ^2.4.15
  hive_ce_generator: ^1.9.2

flutter:
  uses-material-design: true
